# Bagging Classification

## Objective

The objective of this notebook is to build a Bagging Classification model that predicts an employee's salary category.

In this notebook, you will learn how to:

- Load the dataset
- Handle missing values
- Define features and target variable
- Split the dataset into training and testing sets
- Scale the features
- Train a Decision Tree model
- Train a Bagging Classification model
- Compare the performance of both models

In [16]:
# Import Required Libraries

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import BaggingClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

**Step 1: Mount Google Drive**

Google Drive is mounted to access the dataset and save the trained model.

In [17]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


**Step 2: Load the Dataset**

Load the Employee Salary Classification dataset from Google Drive.

In [18]:
df = pd.read_excel(
    "/content/drive/MyDrive/Datasets/Salary_Logistic_Regression_Multiclass_Classification_Dataset.xlsx"
)

df

,Experience_Years,Education_Level,Age,Monthly_Salary_PKR,Salary_Category
0,1,12.0,22.0,40000,0
1,2,12.0,23.0,45000,0
2,2,14.0,24.0,50000,0
3,3,14.0,25.0,58000,0
4,3,NaN,26.0,65000,0
5,4,16.0,27.0,70000,0
6,4,16.0,28.0,74000,0
7,5,16.0,29.0,82000,1
8,5,18.0,30.0,90000,1
9,6,18.0,31.0,98000,1


## Step 3: Handle Missing Values

Check whether the dataset contains missing values.

If any missing values are found, replace them with the median value of the respective column.

In [19]:
print("\nBefore Filling Missing Values")
print(df.isnull().sum())

df["Education_Level"] = df["Education_Level"].fillna(
    df["Education_Level"].median()
)

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

print("\nAfter Filling Missing Values")

print(df.isnull().sum())


Before Filling Missing Values
Experience_Years      0
Education_Level       2
Age                   1
Monthly_Salary_PKR    0
Salary_Category       0
dtype: int64

After Filling Missing Values
Experience_Years      0
Education_Level       0
Age                   0
Monthly_Salary_PKR    0
Salary_Category       0
dtype: int64


## Step 4: Define Features and Target Variable

The independent variables are:

- Experience Years
- Education Level
- Age

The dependent variable is:

- Salary Category

Salary Categories:

- 0 = Low Salary
- 1 = Medium Salary
- 2 = High Salary
- 3 = Executive Salary

In [20]:
X = df[
    [
        "Experience_Years",
        "Education_Level",
        "Age"
    ]
]

y = df["Salary_Category"]

## Step 5: Split the Dataset

Split the dataset into training and testing sets.

- 80% Training Data
- 20% Testing Data

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

## Step 6: Scale the Features

Standardize the feature values so that each feature has a similar scale.

Feature scaling helps improve the performance of the Bagging Classification model.

In [22]:
scaler = StandardScaler()

X_train = scaler.fit_transform(
    X_train
)

X_test = scaler.transform(
    X_test
)

## Step 7: Train the Decision Tree and Bagging Classification Models

Train a Decision Tree model and then use it as the base estimator for the Bagging Classification model.

The **n_estimators** parameter specifies the number of Decision Trees used in the Bagging model.

In [23]:
decision_tree = DecisionTreeClassifier(
    random_state=42
)

bagging_model = BaggingClassifier(
    estimator=decision_tree,
    n_estimators=100,
    random_state=42
)

bagging_model.fit(
    X_train,
    y_train
)



BaggingClassifier(estimator=DecisionTreeClassifier(random_state=42),
                  n_estimators=100, random_state=42)

## Step 8: Make Predictions

Use both the Decision Tree model and the Bagging Classification model to predict the salary categories for the testing dataset.

In [24]:
# Train the Decision Tree Model

decision_tree.fit(
    X_train,
    y_train
)

# Make Predictions

decision_tree_predictions = decision_tree.predict(
    X_test
)

bagging_predictions = bagging_model.predict(
    X_test
)

## Step 9: Compare Model Accuracy

Calculate and compare the accuracy of the Decision Tree model and the Bagging Classification model.

This comparison helps determine whether Bagging improves the model's performance.

In [25]:
decision_tree_accuracy = accuracy_score(
    y_test,
    decision_tree_predictions
)

bagging_accuracy = accuracy_score(
    y_test,
    bagging_predictions
)

print("Decision Tree Accuracy:")

print(
    round(decision_tree_accuracy * 100,2),
    "%"
)

print()

print("Bagging Accuracy:")

print(
    round(bagging_accuracy * 100,2),
    "%"
)

Decision Tree Accuracy:
90.0 %

Bagging Accuracy:
90.0 %


## Step 10: Display the Confusion Matrix

Display the confusion matrix for the Bagging Classification model.

The confusion matrix compares the actual salary categories with the predicted salary categories.

In [26]:
cm = confusion_matrix(
    y_test,
    bagging_predictions
)

print("Confusion Matrix:")

print(cm)

Confusion Matrix:
[[3 0 0]
 [0 4 1]
 [0 0 2]]


## Step 11: Display the Classification Report

Display the classification report for the Bagging Classification model.

The report includes:

- Precision
- Recall
- F1-Score
- Support

In [27]:
print("Classification Report:")

print()

print(
    classification_report(
        y_test,
        bagging_predictions
    )
)

Classification Report:

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         3
           2       1.00      0.80      0.89         5
           3       0.67      1.00      0.80         2

    accuracy                           0.90        10
   macro avg       0.89      0.93      0.90        10
weighted avg       0.93      0.90      0.90        10



## Step 12: Predict the Salary Category for a New Employee

Predict the salary category for an employee with:

- Experience = 12 Years
- Education Level = 20 Years
- Age = 40 Years

In [28]:
new_employee = scaler.transform(
    [[12,20,40]]
)

prediction = bagging_model.predict(
    new_employee
)

salary_categories = {
    0: "Low Salary",
    1: "Medium Salary",
    2: "High Salary",
    3: "Executive Salary"
}

print("Predicted Salary Category:")

print(
    salary_categories[prediction[0]]
)

Predicted Salary Category:
High Salary


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


# Conclusion

In this notebook, a Bagging Classification model was successfully developed to classify employees into salary categories. A Decision Tree was used as the base estimator, and multiple Decision Trees were combined using the Bagging technique. The performance of the Bagging model was compared with a single Decision Tree model, demonstrating how Bagging can improve prediction accuracy and reduce overfitting.