**Logistic Regression (Binary Classification)**

**Objective**

The objective of this notebook is to build a Logistic Regression model that predicts whether an employee belongs to the High Salary category.

In this notebook, you will learn how to:

- Load a classification dataset
- Handle missing values
- Define features and target variable
- Split the dataset into training and testing sets
- Scale numerical features
- Train a Logistic Regression model
- Make predictions
- Evaluate the model using classification metrics

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

**Step 1: Mount Google Drive**

Google Drive is mounted to access the dataset and save the trained model.

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


**Step 2: Load the Dataset**

Load the Employee Salary Classification dataset from Google Drive.

In [5]:
df = pd.read_excel(
    "/content/drive/MyDrive/Datasets/Salary_Logistic_Regression_Binary_Classification_Dataset.xlsx"
)

df

,Experience_Years,Education_Level,Age,Monthly_Salary_PKR,High_Salary
0,1,12.0,22.0,40000,0
1,2,12.0,23.0,43000,0
2,2,14.0,24.0,50000,0
3,3,14.0,25.0,58000,0
4,3,NaN,26.0,62000,0
5,4,16.0,27.0,72000,0
6,4,16.0,28.0,78000,0
7,5,16.0,29.0,85000,0
8,5,18.0,30.0,95000,0
9,6,18.0,31.0,102000,1


**Step 3: Handle Missing Values**

Check whether the dataset contains missing values.

If any missing values are found, replace them with the median value of the respective column.

In [6]:
print("\nBefore Filling Missing Values")
print(df.isnull().sum())

df["Education_Level"] = df["Education_Level"].fillna(
    df["Education_Level"].median()
)

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

print("\nAfter Filling Missing Values")

print(df.isnull().sum())


Before Filling Missing Values
Experience_Years      0
Education_Level       2
Age                   1
Monthly_Salary_PKR    0
High_Salary           0
dtype: int64

After Filling Missing Values
Experience_Years      0
Education_Level       0
Age                   0
Monthly_Salary_PKR    0
High_Salary           0
dtype: int64


**Step 4: Define Features and Target Variable**

Independent Variables (X):

- Experience_Years
- Education_Level
- Age

Dependent Variable (Y):

- High Salary

In [7]:
X = df[
    [
        "Experience_Years",
        "Education_Level",
        "Age"
    ]
]

y = df["High_Salary"]

print(X.head())
print(y.head())

   Experience_Years  Education_Level   Age
0                 1             12.0  22.0
1                 2             12.0  23.0
2                 2             14.0  24.0
3                 3             14.0  25.0
4                 3             20.0  26.0
0    0
1    0
2    0
3    0
4    0
Name: High_Salary, dtype: int64


**Step 5: Split the Dataset**

Split the dataset into training and testing sets.

- 80% Training Data
- 20% Testing Data

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

**Step 6: Scale the Features**

Scale the numerical features using **StandardScaler** so they have a similar scale.

StandardScaler applies the following formula to each feature:

\[
z=\frac{x-\mu}{\sigma}
\]

Where:

- **x** = Original value
- **μ** = Mean of the feature
- **σ** = Standard deviation of the feature
- **z** = Standardized value

Feature scaling helps Logistic Regression learn more effectively by preventing features with larger values from having a greater influence on the model.

In [19]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

print(X_test)


[[-0.4517625   0.24285329 -0.36083873]
 [-0.4517625  -0.40475548 -0.36083873]
 [ 1.19101024  0.89046206  1.16320064]
 [-0.68644432 -0.40475548 -0.62978686]
 [-0.21708068  0.24285329 -0.00224123]
 [ 0.36962387  0.89046206  0.53565502]
 [ 0.7216466   0.89046206  0.80460314]
 [ 0.60430569  0.89046206  0.71495377]
 [ 1.42569206  0.89046206  1.34249939]
 [-0.09973977  0.89046206  0.17705752]]


**Step 7: Train the Logistic Regression Model**

Train the Logistic Regression model using the training dataset.

In [11]:
model = LogisticRegression()

model.fit(X_train, y_train)



LogisticRegression()

**Step 8: Make Predictions**

Predict the High Salary category using the testing dataset.

In [12]:
y_pred = model.predict(X_test)

print(y_pred)

[1 1 1 1 1 1 1 1 1 1]


**Step 9: Calculate Accuracy**

Measure the percentage of correct predictions made by the model.

In [13]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:")

print(round(accuracy * 100,2),"%")

Accuracy:
100.0 %


**Step 10: Display the Confusion Matrix**

A **Confusion Matrix** is a table used to evaluate the performance of a classification model by comparing the **actual values** with the **predicted values**.

It summarizes the model's predictions into four possible outcomes:

- **True Positive (TP):** The employee actually belongs to the **High Salary** category, and the model correctly predicts **High Salary**.
- **True Negative (TN):** The employee actually belongs to the **Normal Salary** category, and the model correctly predicts **Normal Salary**.
- **False Positive (FP):** The employee actually belongs to the **Normal Salary** category, but the model incorrectly predicts **High Salary**.
- **False Negative (FN):** The employee actually belongs to the **High Salary** category, but the model incorrectly predicts **Normal Salary**.

The confusion matrix helps identify where the model makes correct predictions and where it makes classification errors.

In [14]:
cm = confusion_matrix(y_test,y_pred)

print(cm)

[[10]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


**Step 11: Display the Classification Report**

The classification report provides detailed performance metrics for the classification model.

It includes:

- **Precision:** When the model predicts **"High Salary,"** how often is it correct?
- **Recall:** Out of all actual **"High Salary"** employees, how many did the model correctly identify?
- **F1-Score:** A balanced measure that combines Precision and Recall into a single performance metric.
- **Support:** The number of actual observations belonging to each class in the testing dataset.

> **Note:** Accuracy is calculated separately in the previous step because it measures the model's overall correctness, whereas the classification report focuses on evaluating each class individually.

In [16]:

print(classification_report(y_test, y_pred))



              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



**Step 12: Predict the Salary Category for a New Employee**

Predict whether a new employee belongs to the High Salary category.

Employee Details:

- Experience = 10 Years
- Education Level = 18 Years
- Age = 35 Years

In [17]:
new_employee = scaler.transform(
    [[10, 18, 35]]
)

prediction = model.predict(
    new_employee
)

print("Prediction:")

if prediction[0] == 1:
    print("High Salary")
else:
    print("Normal Salary")

Prediction:
High Salary


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


**Conclusion**

In this notebook, a Logistic Regression model was successfully developed to solve a binary classification problem. The dataset was preprocessed by handling missing values, splitting it into training and testing sets, and scaling the numerical features.

The trained model was then used to classify employees into High Salary and Normal Salary categories. Finally, the model's performance was evaluated using accuracy, a confusion matrix, and a classification report, demonstrating the complete workflow for building and assessing a binary classification model.